### ISSUE TITLE
Implement StockDetail MVP

### ISSUE THREAD

**Issue by ragegage** [ragegage/robinbanks#44]
Objective: StockDetail shows StockCharts and StockNews

**Comment by ragegage** [comment]
Pieces implemented at a basic level, but MVP not obtained yet.
Should only be an hour or two more of work.

**Comment by ragegage** [comment]
- [x] Put current price in h1 at top of chart
- [x] Put %change over the past X in h4 above chart
- [x] Fix hover on chart
- [x] Add coloring to StocksIndex (red -> bad news, green -> good news)
- [x] Add coloring to StockChart (red -> bad news, green -> good news)

**Comment by ragegage** [comment]
Could only change the color of StockChart .chart-main-details; the chart doesn't re-render the color when the data changes for some reason.

**Comment by ragegage** [comment]
Implemented during StockChart chart rebuild.
